version: "3.9"
services:
  openldap:
    image: osixia/openldap:latest
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: "DC=example,DC=org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
    command: --copy-service --loglevel debug
    volumes:
      - ./configs/ldap/schema:/container/service/slapd/assets/config/bootstrap/schema/custom
      - ./configs/ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

  nfs:
    image: itsthenetwork/nfs-server-alpine:12
    privileged: true
    environment:
      - SHARED_DIRECTORY=/nfs
    volumes:
      - /tmp/nfs:/nfs
    ports:
      - 2049:2049

  proxy:
    image: nginx:latest
    ports:
      - 3000:80
      - 3001:443
    volumes:
      - ./configs/proxy/nginx.crt:/etc/ssl/nginx.crt
      - ./configs/proxy/nginx.key:/etc/ssl/nginx.key
      - ./configs/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - overseer

  mqtt:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  virtsrv:
    build: modules/virtualization-server
    volumes:
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
      - /var/lib/libvirt/:/var/lib/libvirt/
      - ${HOME}/.vagrant.d/boxes/:/root/.vagrant.d/boxes/
      - ./configs/virtsrv:/app/config
      - ~/.vagrant.d/boxes/smogork-VAGRANTSLASH-archlinux-rdp/0.2.1/libvirt/nvram.fd:/app/nvram.fd
    depends_on:
      - overseer
      - nfs
    entrypoint:
      [
        "/wait-for-it.sh",
        "-t",
        "30",
        "-s",
        "overseer:5000",
        "--",
        "/bin/bash",
        "entry_point.sh"
      ]

  overseer:
    build: modules/overseer
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./configs/overseer:/overseer/config
      - ./configs/overseer/overseer.pfx:/overseer/overseer.pfx
    depends_on:
      - mqtt
      - openldap
    entrypoint:
      [
        "/wait-for-it.sh",
        "-t",
        "30",
        "-s",
        "mqtt:5672",
        "--",
        "/bin/bash",
        "entry_point.sh"
      ]

  admin-panel:
    build: modules/admin-panel
    ports:
      - 4000:80
      - 4001:443
    volumes:
      - ./configs/admin-panel/nginx.crt:/etc/ssl/nginx.crt
      - ./configs/admin-panel/nginx.key:/etc/ssl/nginx.key
      - ./configs/admin-panel/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - API_URL=http://localhost:3000
    depends_on:
      - overseer
