version: "3.9"
services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.crt:/etc/ssl/nginx.crt
      - ./nginx.key:/etc/ssl/nginx.key
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - overseer1
      - overseer2


  mqtt:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  overseer1:
    build: ../modules/overseer
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ../configs/overseer:/overseer/config
      - ../configs/overseer/overseer.pfx:/overseer/overseer.pfx
    depends_on:
      - mqtt
    entrypoint:
      [
        "/wait-for-it.sh",
        "-t",
        "30",
        "-s",
        "mqtt:5672",
        "--",
        "/bin/bash",
        "entry_point.sh"
      ]

  overseer2:
    build: ../modules/overseer
    ports:
      - 5002:5000
      - 5003:5001
    volumes:
      - ../configs/overseer:/overseer/config
      - ../configs/overseer/overseer.pfx:/overseer/overseer.pfx
    depends_on:
      - mqtt
    entrypoint:
      [
        "/wait-for-it.sh",
        "-t",
        "30",
        "-s",
        "mqtt:5672",
        "--",
        "/bin/bash",
        "entry_point.sh"
      ]
